version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: online-exam
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - binarypoint-network
      - mysql-network
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST : mysql-database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - binarypoint-network
      - mysql-network    

volumes:
  mysql-data:
  
networks:
  mysql-network:
    driver: bridge
  binarypoint-network:
    external: true