version: '3.8'
name: wp-varnish-demo-test
services:
  wp:
    image: maniknp/wp-cli:1.0-php8.2-alpine
    # restart: always
    container_name: wp-app
    volumes:
      - ./config/php/docker-php-entrypoint.sh:/usr/local/bin/docker-php-entrypoint
      - ./config/php/docker-entrypoint.d:/docker-entrypoint.d
      - ./config/php/php.ini-dev:/usr/local/etc/php/php.ini
      - ${WP_DEMO_ROOT}
    environment:
      - DB_HOST=mysql-database
      - DB_PORT=3306
      - DB_DATABASE=wp
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword

    networks:
      - wp-varnish-demo-test-network
      - binarypoint-network
    #depends_on:
    #   - db

  nginx:
    image: maniknp/nginx:1.27.3-brotli
    container_name: nginx-container
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ${WP_DEMO_ROOT}
    ports:
      - 80:80
    networks:
      - wp-varnish-demo-test-network
    depends_on:
      - wp

# volumes:
  #db_data:
  #wordpress_data:

networks:
  wp-varnish-demo-test-network:
    driver: bridge
  binarypoint-network:
    external: true